### ISSUE TITLE
The initial position of the hands use transitions

### ISSUE THREAD

**Issue by gbraad** [gbraad-vscode/analogue-clock#1]
This makes the hands flop in to place.

```css
.hand {
    transition: none;
}

.hand.animate {
    transition: transform 0.5s cubic-bezier(0.2, 0.8, 0.2, 1.2);
}

#secondHand.animate {
    transition: transform 0.3s cubic-bezier(0.2, 0.8, 0.2, 1.2);
}
```

and after updating the clock hands:

```html
    document.querySelectorAll('.hand').forEach(hand => {
        hand.classList.add('animate');
    });
```

does not work as expected.
